name: Sync to Organization Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: linux-x64-medium

    steps:
      - name: Checkout source repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Configure Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Check if PAT is present
        run: |
          if [ -z "${{ secrets.PAT_SYNC }}" ]; then
            echo "PAT is missing!"
          else:
            echo "PAT is there"
          fi

      - name: Add destination repo remote
        run: |
          git remote add dest https://x-access-token:${{ secrets.PAT_SYNC }}@github.com/mmtesthoro/urban-memory.git

      - name: Push to destination repo
        run: |
          git push dest main --force
